fixed json case + added episode ids + empty response error
jellyfin/jellyfin-plugin-simkl pull request #25
Opened 2023-11-01 13:10 UTC by ekleop

it works really bad(only detection by file available) without this fixes.

2023-11-01 13:23 UTC, JamsRepos commented
Been working to test these new changes and full functionality has now been restored. Without this update, Shows will not scrobble past Season 1.

2023-11-02 13:54 UTC, crobibero requested changes

2023-11-02 13:54 UTC, crobibero commented on Jellyfin.Plugin.Simkl/Jellyfin.Plugin.Simkl.csproj
This file's changes should be reverted

2023-11-02 18:09 UTC, ekleop commented on Jellyfin.Plugin.Simkl/Jellyfin.Plugin.Simkl.csproj
done, then the version will be the same 3.0.0

2023-11-02 18:10 UTC, ekleop commented on Jellyfin.Plugin.Simkl/API/SimklApi.cs
> +            };
ok, didn't take into account the performance issue. Fixed.

2023-11-02 18:43 UTC, crobibero approved these changes

2023-11-02 18:43 UTC, merged